spring:
  data:
    redis:
      host: localhost
      port: 16379
      database: 0
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/hotels_db
    username: hotels_user
    password: hotels12345
#  jpa:
#    hibernate:
#      ddl-auto: update

file:
  upload-dir: D:/image/
  resource-handler: /images/**

#JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
cors:
  allowed-origins: http://localhost:3000,http://127.0.0.1:3000, http://localhost:8080, http://localhost:8085, http://tomhoon.my:780